package com.yokke.merchantservice.merchant;

import com.yokke.base.mapper.BaseMapper;
import org.springframework.stereotype.Service;

@Service
public class MerchantMapper extends BaseMapper {
    public MerchantDto mapToDto(Merchant merchantMain) {
        return MerchantDto.builder()
                .mid(merchantMain.getMid())
                .aplcSeqNo(merchantMain.getAplcSeqNo())
                .merNm(merchantMain.getMerNm())
                .merDtlAddr1(merchantMain.getMerDtlAddr1())
                .merDtlAddr2(merchantMain.getMerDtlAddr2())
                .merDtlAddr3(merchantMain.getMerDtlAddr3())
                .merPost(merchantMain.getMerPost())
                .merMailIno(merchantMain.getMerMailIno())
                .merCityCd(merchantMain.getMerCityCd())
                .maiTrtItmsNm(merchantMain.getMaiTrtItmsNm())
                .slsStrtDate(merchantMain.getSlsStrtDate())
                .merTelRgnCd(merchantMain.getMerTelRgnCd())
                .merTelNo(merchantMain.getMerTelNo())
                .merFaxTelRgnCd(merchantMain.getMerFaxTelRgnCd())
                .merFaxTelNo(merchantMain.getMerFaxTelNo())
                .hpgeUrl(merchantMain.getHpgeUrl())
                .stdTiznCd(merchantMain.getStdTiznCd())
                .brndClcd(merchantMain.getBrndClcd())
                .mccCd(merchantMain.getMccCd())
                .brndClcd1(merchantMain.getBrndClcd1())
                .mccCd1(merchantMain.getMccCd1())
                .merSegmtCd(merchantMain.getMerSegmtCd())
                .emailAddr(merchantMain.getEmailAddr())
                .strtSlsTime(merchantMain.getStrtSlsTime())
                .endSlsTime(merchantMain.getEndSlsTime())
                .bthMgrFnm1(merchantMain.getBthMgrFnm1())
                .bthMgrFnm2(merchantMain.getBthMgrFnm2())
                .bthMgrTelRgnCd(merchantMain.getBthMgrTelRgnCd())
                .bthMgrTelNo(merchantMain.getBthMgrTelNo())
                .bthMgrHpTelNo11(merchantMain.getBthMgrHpTelNo11())
                .bthMgrHpTelNo12(merchantMain.getBthMgrHpTelNo12())
                .bthMgrHpTelNo21(merchantMain.getBthMgrHpTelNo21())
                .bthMgrHpTelNo22(merchantMain.getBthMgrHpTelNo22())
                .pmtAcctBkCd(merchantMain.getPmtAcctBkCd())
                .acctMgmtBkCd(merchantMain.getAcctMgmtBkCd())
                .pmtAcctNo(merchantMain.getPmtAcctNo())
                .acctTpCd(merchantMain.getAcctTpCd())
                .pmtAcctDpsoNm(merchantMain.getPmtAcctDpsoNm())
                .pmtAcctBrCd(merchantMain.getPmtAcctBrCd())
                .offclMerNm(merchantMain.getOffclMerNm())
                .offclMerDtlAddr1(merchantMain.getOffclMerDtlAddr1())
                .offclMerDtlAddr2(merchantMain.getOffclMerDtlAddr2())
                .offclMerDtlAddr3(merchantMain.getOffclMerDtlAddr3())
                .offclMerPost(merchantMain.getOffclMerPost())
                .offclMerMailIno(merchantMain.getOffclMerMailIno())
                .offclMerCityCd(merchantMain.getOffclMerCityCd())
                .offclMerTelRgnCd(merchantMain.getOffclMerTelRgnCd())
                .offclMerTelNo(merchantMain.getOffclMerTelNo())
                .offclMerFaxTelRgnCd(merchantMain.getOffclMerFaxTelRgnCd())
                .offclMerFaxTelNo(merchantMain.getOffclMerFaxTelNo())
                .offclMerHpgeUrl(merchantMain.getOffclMerHpgeUrl())
                .ktpno(merchantMain.getKtpno())
                .npwp(merchantMain.getNpwp())
                .dtlBizTpCtnts(merchantMain.getDtlBizTpCtnts())
                .newRegtDate(merchantMain.getNewRegtDate())
                .newRegtTime(merchantMain.getNewRegtTime())
                .build();
    }
}
