export type OwnerDto = {
  mid: string;
  ktpno: string;
  rpsvNm: string;
  homDtlAddr1: string;
  homDtlAddr2: string;
  homDtlAddr3: string;
  homPost: null;
  homMailIno: null;
  rpsvCityCd: string;
  homTelRgnCd: string;
  homTelNo: string;
  rpsvHpTelNo1: string;
  rpsvHpTelNo2: null;
  rpsvFaxTelRgnCd: null;
  rpsvFaxTelNo: null;
  rpsvEmailAddr: null;
  inpUsrId: string;
  inpPgmId: string;
  dataInpDttm: Date;
  chngUsrId: string;
  chngPgmId: string;
  dataChngDttm: Date;
};
