export type CddDto = {
  cmmnCdId: string;
  dtlCdId: string;
  dtlCdNm: string;
  cdExpl: string;
  sortSeq: number;
  clssInfoVal1?: string;
  clssInfoVal2?: string;
  clssInfoVal3?: string;
  clssInfoVal4?: string;
  clssInfoVal5?: string;
  clssInfoVal6?: string;
  dataStatCd: string;
  inpUsrId: string;
  inpPgmId: string;
  dataInpDttm: Date;
  chngUsrId: string;
  chngPgmId: string;
  dataChngDttm: Date;
};
